export const countries = [
  { country: 'Belgium', countryisocode: 'BE' },
  { country: 'Bulgaria', countryisocode: 'BG' },
  { country: 'Chile', countryisocode: 'CL' },
  { country: 'China', countryisocode: 'CN' },
  { country: 'Colombia', countryisocode: 'CO' },
  { country: 'Egypt', countryisocode: 'EG' },
  { country: 'Finland', countryisocode: 'FI' },
  { country: 'France', countryisocode: 'FR' },
  { country: 'Germany', countryisocode: 'DE' },
  { country: 'Hong Kong', countryisocode: 'HK' },
  { country: 'India', countryisocode: 'IN' },
  { country: 'Ireland', countryisocode: 'IE' },
  { country: 'Italy', countryisocode: 'IT' },
  { country: 'Japan', countryisocode: 'JP' },
  { country: 'Kenya', countryisocode: 'KE' },
  { country: 'Macau', countryisocode: 'MO' },
  { country: 'Malta', countryisocode: 'MT' },
  { country: 'Mexico', countryisocode: 'MX' },
  { country: 'New Zealand', countryisocode: 'NZ' },
  { country: 'Peru', countryisocode: 'PE' },
  { country: 'Spain', countryisocode: 'ES' },
  { country: 'Taiwan', countryisocode: 'TW' },
  { country: 'Thailand', countryisocode: 'TH' },
  { country: 'United Kingdom', countryisocode: 'GB' },
  { country: 'United States', countryisocode: 'US' },
];
