export const hotels = [
  {
    chain_name: 'Samed Resorts Group',
    hotel_name: 'Sai Kaew Beach Resort',
    addressline1: '8/1 Moo 4 Tumbon Phe Muang',
    addressline2: '',
    zipcode: '21160',
    city: 'Koh Samet',
    state: 'Rayong',
    country: 'Thailand',
    countryisocode: 'TH',
    star_rating: 4,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Marine Hotel',
    addressline1: 'Sutton Cross',
    addressline2: '',
    zipcode: 'D13',
    city: 'Dublin',
    state: '',
    country: 'Ireland',
    countryisocode: 'IE',
    star_rating: 3,
  },
  {
    chain_name: 'Melia Hotels International',
    hotel_name: 'TRYP Malaga Alameda Hotel',
    addressline1: 'Avenida de la Aurora CC.Larios Centro S/N',
    addressline2: '',
    zipcode: '29002',
    city: 'Malaga',
    state: 'Andalusia',
    country: 'Spain',
    countryisocode: 'ES',
    star_rating: 4,
  },
  {
    chain_name: 'NH Hotels',
    hotel_name: 'NH Iquique Hotel',
    addressline1: 'Av Costanera 3939',
    addressline2: '',
    zipcode: '1111500',
    city: 'Iquique',
    state: 'Tarapacá',
    country: 'Chile',
    countryisocode: 'CL',
    star_rating: 4,
  },
  {
    chain_name: 'Marriott',
    hotel_name: 'Sheraton Grand Hotel & Spa, Edinburgh',
    addressline1: '1 Festival Square',
    addressline2: '',
    zipcode: 'EH39SR',
    city: 'Edinburgh',
    state: 'Scotland',
    country: 'United Kingdom',
    countryisocode: 'GB',
    star_rating: 5,
  },
  {
    chain_name: 'HK CTS Hotels',
    hotel_name: 'Kew Green Hotel Wanchai Hong Kong',
    addressline1: '41-49 Hennessy Road',
    addressline2: '',
    zipcode: '',
    city: 'Hong Kong',
    state: 'Hong Kong',
    country: 'Hong Kong',
    countryisocode: 'HK',
    star_rating: 4,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Hotel Dann Carlton Medellin',
    addressline1: 'Cra 43A No. 7-50',
    addressline2: '',
    zipcode: '50001',
    city: 'Medellin',
    state: '',
    country: 'Colombia',
    countryisocode: 'CO',
    star_rating: 5,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Grand Coloane Resort',
    addressline1: '1918 Estrada de Hac Sa',
    addressline2: '',
    zipcode: '',
    city: 'Macau',
    state: 'Macao',
    country: 'Macau',
    countryisocode: 'MO',
    star_rating: 5,
  },
  {
    chain_name: 'Skycity',
    hotel_name: 'SKYCITY Hotel',
    addressline1: 'Corner Victoria & Federal Streets',
    addressline2: '',
    zipcode: '1010',
    city: 'Auckland',
    state: 'Auckland',
    country: 'New Zealand',
    countryisocode: 'NZ',
    star_rating: 4.5,
  },
  {
    chain_name: 'Accor Hotels',
    hotel_name: 'Pullman Bordeaux Lac',
    addressline1: 'Avenue Jean Gabriel Domergue',
    addressline2: '',
    zipcode: '33300',
    city: 'Bordeaux',
    state: 'Aquitaine',
    country: 'France',
    countryisocode: 'FR',
    star_rating: 4,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Hotel Conde Luna',
    addressline1: 'Avenida Independencia, 7',
    addressline2: '',
    zipcode: '24003',
    city: 'Leon',
    state: '',
    country: 'Spain',
    countryisocode: 'ES',
    star_rating: 4,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Park Suisse Hotel',
    addressline1: 'Via Favale 31',
    addressline2: '',
    zipcode: '16038',
    city: 'Santa Margherita Ligure',
    state: 'Liguria',
    country: 'Italy',
    countryisocode: 'IT',
    star_rating: 4,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Hotel Agua Escondida',
    addressline1: 'Guillermo Spartling, 4 Centro ',
    addressline2: '',
    zipcode: '40200',
    city: 'Taxco',
    state: '',
    country: 'Mexico',
    countryisocode: 'MX',
    star_rating: 4,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Hotel Caribe Cartagena',
    addressline1: 'Carrera 1, 2-87, Bocagrande',
    addressline2: '',
    zipcode: '130001',
    city: 'Cartagena',
    state: 'Bolivar',
    country: 'Colombia',
    countryisocode: 'CO',
    star_rating: 5,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Haihua Hotel Hangzhou',
    addressline1: 'No. 298, Qing Chun Road',
    addressline2: '',
    zipcode: '310006',
    city: 'Hangzhou',
    state: 'Zhejiang',
    country: 'China',
    countryisocode: 'CN',
    star_rating: 4,
  },
  {
    chain_name: 'Tokyu Hotels',
    hotel_name: 'Kobe Sannomiya Tokyu REI Hotel',
    addressline1: '6-1-5 Kumoidori, Chuo-ku',
    addressline2: '',
    zipcode: '651-0096',
    city: 'Kobe',
    state: 'Hyogo',
    country: 'Japan',
    countryisocode: 'JP',
    star_rating: 3,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Suites South Burlington',
    addressline1: '1712 Shelburne Rd.',
    addressline2: '',
    zipcode: '5403',
    city: 'So Burlington (VT)',
    state: 'Vermont',
    country: 'United States',
    countryisocode: 'US',
    star_rating: 2.5,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Everbright Convention & Exhibition Centre International Hotel',
    addressline1: '66 Caobao Road, Xuhui district',
    addressline2: '',
    zipcode: '',
    city: 'Shanghai',
    state: 'Shanghai',
    country: 'China',
    countryisocode: 'CN',
    star_rating: 4,
  },
  {
    chain_name: 'Hilton Worldwide',
    hotel_name: 'Hilton Garden Inn Pittsburgh University Place',
    addressline1: '3454 Forbes Avenue',
    addressline2: '',
    zipcode: '15213',
    city: 'Pittsburgh (PA)',
    state: 'Pennsylvania',
    country: 'United States',
    countryisocode: 'US',
    star_rating: 3,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Hotel Apogia Nice',
    addressline1: '26, Rue Smolett',
    addressline2: '',
    zipcode: '6300',
    city: 'Nice',
    state: "Provence-Alpes-Cote d'Azur",
    country: 'France',
    countryisocode: 'FR',
    star_rating: 4,
  },
  {
    chain_name: 'Caesars Entertainment Corporation',
    hotel_name: 'Paris Las Vegas',
    addressline1: '3655 Las Vegas Boulevard South',
    addressline2: '',
    zipcode: '89109',
    city: 'Las Vegas (NV)',
    state: 'Nevada',
    country: 'United States',
    countryisocode: 'US',
    star_rating: 4,
  },
  {
    chain_name: 'Hoteles Catalonia',
    hotel_name: 'Catalonia Brussels Hotel',
    addressline1: 'Avenue du Haut-Pont, 2 Hoge Bruglaan',
    addressline2: '',
    zipcode: 'B1060',
    city: 'Brussels',
    state: 'Brussels-Capital',
    country: 'Belgium',
    countryisocode: 'BE',
    star_rating: 3,
  },
  {
    chain_name: 'Prince Hotels',
    hotel_name: 'Grand Prince Hotel Shin Takanawa',
    addressline1: '3-13-1 Takanawa, Minato-ku',
    addressline2: '',
    zipcode: '108-8612',
    city: 'Tokyo',
    state: 'Tokyo',
    country: 'Japan',
    countryisocode: 'JP',
    star_rating: 4,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Watazen Ryokan Hotel',
    addressline1: '604-8113 Nakagyo-ku Yanaginobaba-dori Rokkaku-kudaru 413',
    addressline2: '',
    zipcode: '604-8113',
    city: 'Kyoto',
    state: 'Kyoto',
    country: 'Japan',
    countryisocode: 'JP',
    star_rating: 3,
  },
  {
    chain_name: 'Thistle & Guoman',
    hotel_name: 'Amba Hotel Charing Cross',
    addressline1: 'The Strand',
    addressline2: '',
    zipcode: 'WC2N 5HX',
    city: 'London',
    state: 'London, England',
    country: 'United Kingdom',
    countryisocode: 'GB',
    star_rating: 4,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Imperial Hotel',
    addressline1: '32-34 Nathan Road',
    addressline2: '',
    zipcode: '',
    city: 'Hong Kong',
    state: 'Hong Kong',
    country: 'Hong Kong',
    countryisocode: 'HK',
    star_rating: 3,
  },
  {
    chain_name: 'Leading Hotels of the World',
    hotel_name: 'Royal Hotel Sanremo',
    addressline1: '80 Corso Imperatrice',
    addressline2: '',
    zipcode: '18038',
    city: 'Sanremo',
    state: '',
    country: 'Italy',
    countryisocode: 'IT',
    star_rating: 5,
  },
  {
    chain_name: 'Park Hotels',
    hotel_name: 'The Park Hotel Visakhapatnam',
    addressline1: 'Beach road',
    addressline2: '',
    zipcode: '530023',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    country: 'India',
    countryisocode: 'IN',
    star_rating: 5,
  },
  {
    chain_name: 'InterContinental Hotels Group',
    hotel_name: 'Staybridge Suites Austin Round Rock',
    addressline1: '520 S IH 35 Frontage Rd',
    addressline2: '',
    zipcode: '78681',
    city: 'Round Rock (TX)',
    state: 'Texas',
    country: 'United States',
    countryisocode: 'US',
    star_rating: 3,
  },
  {
    chain_name: 'Sotetsu Fresa Inn',
    hotel_name: 'Hotel Sunroute Nara',
    addressline1: '1110 Takabatake-cho',
    addressline2: '',
    zipcode: '630-8301',
    city: 'Nara',
    state: 'Nara',
    country: 'Japan',
    countryisocode: 'JP',
    star_rating: 3,
  },
  {
    chain_name: 'Thistle & Guoman',
    hotel_name: 'The Tower Hotel',
    addressline1: "St Katharine's Way",
    addressline2: '',
    zipcode: 'E1W 1LD',
    city: 'London',
    state: 'London, England',
    country: 'United Kingdom',
    countryisocode: 'GB',
    star_rating: 4,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'The Grand New Delhi Hotel',
    addressline1: 'Nelson Mandela Road, Vasant Kunj, Phase II',
    addressline2: '',
    zipcode: '110070',
    city: 'New Delhi and NCR',
    state: 'Delhi National Territory',
    country: 'India',
    countryisocode: 'IN',
    star_rating: 5,
  },
  {
    chain_name: 'Corinthia Hotels International',
    hotel_name: 'Corinthia Hotel St. George’s Bay',
    addressline1: 'St. George`s Bay',
    addressline2: '',
    zipcode: 'STJ 3301',
    city: "St. Julian's",
    state: 'Malta',
    country: 'Malta',
    countryisocode: 'MT',
    star_rating: 5,
  },
  {
    chain_name: 'Blue Sea Hotels & Resorts',
    hotel_name: 'Gran Hotel Cervantes by Blue Sea',
    addressline1: 'Las Mercedes s/n',
    addressline2: '',
    zipcode: '29620',
    city: 'Torremolinos',
    state: 'Andalusia',
    country: 'Spain',
    countryisocode: 'ES',
    star_rating: 4,
  },
  {
    chain_name: 'InterContinental Hotels Group',
    hotel_name: 'Hotel Intercontinental Cali',
    addressline1: 'Av. Colombia No. 2-72',
    addressline2: '',
    zipcode: '760001',
    city: 'Cali',
    state: 'Valle del Cauca',
    country: 'Colombia',
    countryisocode: 'CO',
    star_rating: 4.5,
  },
  {
    chain_name: 'Oberoi Hotels & Resorts',
    hotel_name: 'The Oberoi Rajvilas Jaipur Hotel',
    addressline1: 'Goner Road',
    addressline2: '',
    zipcode: '303012',
    city: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    countryisocode: 'IN',
    star_rating: 5,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Mariel Hotel Boutique',
    addressline1: 'General Belisario Suarez, 240 - Miraflores',
    addressline2: '',
    zipcode: 'Lima18',
    city: 'Lima',
    state: '',
    country: 'Peru',
    countryisocode: 'PE',
    star_rating: 3,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Hilton Hurghada Long Beach Resort',
    addressline1: 'Sahl Hashish Red Sea',
    addressline2: '',
    zipcode: '                    ',
    city: 'Hurghada',
    state: 'Al Bahr al Ahmar',
    country: 'Egypt',
    countryisocode: 'EG',
    star_rating: 3,
  },
  {
    chain_name: 'Daiwa Royal Hotel',
    hotel_name: 'Royal Hotel MUNAKATA',
    addressline1: '1303 Tano, Munakata-shi',
    addressline2: '',
    zipcode: '811-3514',
    city: 'Munakata',
    state: 'Fukuoka',
    country: 'Japan',
    countryisocode: 'JP',
    star_rating: 4,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Gioberti Hotel',
    addressline1: 'Via Gioberti 20',
    addressline2: '',
    zipcode: '185',
    city: 'Rome',
    state: 'Lazio',
    country: 'Italy',
    countryisocode: 'IT',
    star_rating: 4,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Hotel Serrano',
    addressline1: 'Marques de Villamejor, 8',
    addressline2: '',
    zipcode: '28006',
    city: 'Madrid',
    state: 'Madrid',
    country: 'Spain',
    countryisocode: 'ES',
    star_rating: 4,
  },
  {
    chain_name: '',
    hotel_name: 'Sarova Whitesands Beach Resort & Spa',
    addressline1: 'Nyali/Malindi Highway',
    addressline2: '',
    zipcode: '801',
    city: 'Mombasa',
    state: 'Mombasa',
    country: 'Kenya',
    countryisocode: 'KE',
    star_rating: 5,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Scandic Seinajoki',
    addressline1: 'Kauppakatu 10',
    addressline2: '',
    zipcode: '60100',
    city: 'Seinajoki',
    state: '',
    country: 'Finland',
    countryisocode: 'FI',
    star_rating: 4,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Van der Valk Hotel Hildesheim',
    addressline1: 'Markt 4, GPS: Jakobistraße',
    addressline2: '',
    zipcode: '31134',
    city: 'Hildesheim',
    state: '',
    country: 'Germany',
    countryisocode: 'DE',
    star_rating: 4,
  },
  {
    chain_name: 'Marriott',
    hotel_name: 'Sheraton Grand Taipei Hotel',
    addressline1: 'No.12, Sec. 1, Zhongxiao E. Rd',
    addressline2: '',
    zipcode: '10049',
    city: 'Taipei',
    state: 'Taipei City',
    country: 'Taiwan',
    countryisocode: 'TW',
    star_rating: 5,
  },
  {
    chain_name: 'InterContinental Hotels Group',
    hotel_name: 'Holiday Inn Express London Greenwich',
    addressline1: 'Bugsbys Way',
    addressline2: '',
    zipcode: 'SE10 0GD',
    city: 'London',
    state: 'London, England',
    country: 'United Kingdom',
    countryisocode: 'GB',
    star_rating: 3.5,
  },
  {
    chain_name: 'No chain',
    hotel_name: 'Bulgaria Hotel',
    addressline1: '21 Alexandrovska Street',
    addressline2: '',
    zipcode: '8000',
    city: 'Burgas',
    state: '',
    country: 'Bulgaria',
    countryisocode: 'BG',
    star_rating: 4,
  },
];
